"""Create walk forward evaluations table

Revision ID: 133a0cddab7e
Revises: 48ab9e5f0b88
Create Date: 2026-07-11 12:25:01.963645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133a0cddab7e'
down_revision: Union[str, Sequence[str], None] = '48ab9e5f0b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_forward_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('home_history_matches', sa.Integer(), nullable=False),
    sa.Column('away_history_matches', sa.Integer(), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=False),
    sa.Column('away_xg', sa.Float(), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=False),
    sa.Column('draw_probability', sa.Float(), nullable=False),
    sa.Column('away_win_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_result', sa.String(), nullable=False),
    sa.Column('actual_result', sa.String(), nullable=False),
    sa.Column('result_correct', sa.Boolean(), nullable=False),
    sa.Column('predicted_home_score', sa.Integer(), nullable=False),
    sa.Column('predicted_away_score', sa.Integer(), nullable=False),
    sa.Column('actual_home_score', sa.Integer(), nullable=False),
    sa.Column('actual_away_score', sa.Integer(), nullable=False),
    sa.Column('score_correct', sa.Boolean(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=False),
    sa.Column('goal_error', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walk_forward_evaluations_away_team_id'), 'walk_forward_evaluations', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_walk_forward_evaluations_competition_id'), 'walk_forward_evaluations', ['competition_id'], unique=False)
    op.create_index(op.f('ix_walk_forward_evaluations_fixture_id'), 'walk_forward_evaluations', ['fixture_id'], unique=True)
    op.create_index(op.f('ix_walk_forward_evaluations_home_team_id'), 'walk_forward_evaluations', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_walk_forward_evaluations_id'), 'walk_forward_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_walk_forward_evaluations_kickoff_time'), 'walk_forward_evaluations', ['kickoff_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walk_forward_evaluations_kickoff_time'), table_name='walk_forward_evaluations')
    op.drop_index(op.f('ix_walk_forward_evaluations_id'), table_name='walk_forward_evaluations')
    op.drop_index(op.f('ix_walk_forward_evaluations_home_team_id'), table_name='walk_forward_evaluations')
    op.drop_index(op.f('ix_walk_forward_evaluations_fixture_id'), table_name='walk_forward_evaluations')
    op.drop_index(op.f('ix_walk_forward_evaluations_competition_id'), table_name='walk_forward_evaluations')
    op.drop_index(op.f('ix_walk_forward_evaluations_away_team_id'), table_name='walk_forward_evaluations')
    op.drop_table('walk_forward_evaluations')
    # ### end Alembic commands ###
