"""Add external_id to players

Revision ID: 6706a99d0c16
Revises: 8ce9a662b6c6
Create Date: 2026-07-03 21:01:42.325115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6706a99d0c16'
down_revision: Union[str, Sequence[str], None] = '8ce9a662b6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('external_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'external_id')
    # ### end Alembic commands ###
