"""Create team ratings table

Revision ID: 95e9bd877a79
Revises: cc466e2506af
Create Date: 2026-07-05 07:34:50.900990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e9bd877a79'
down_revision: Union[str, Sequence[str], None] = 'cc466e2506af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('attack_rating', sa.Float(), nullable=False),
    sa.Column('defense_rating', sa.Float(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_team_ratings_id'), 'team_ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_ratings_id'), table_name='team_ratings')
    op.drop_table('team_ratings')
    # ### end Alembic commands ###
