"""Create home away team stats table

Revision ID: b73a50938c64
Revises: f62518ba1b91
Create Date: 2026-07-05 05:32:35.313074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73a50938c64'
down_revision: Union[str, Sequence[str], None] = 'f62518ba1b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_home_away_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('home_matches', sa.Integer(), nullable=True),
    sa.Column('home_wins', sa.Integer(), nullable=True),
    sa.Column('home_draws', sa.Integer(), nullable=True),
    sa.Column('home_losses', sa.Integer(), nullable=True),
    sa.Column('home_goals_for', sa.Integer(), nullable=True),
    sa.Column('home_goals_against', sa.Integer(), nullable=True),
    sa.Column('away_matches', sa.Integer(), nullable=True),
    sa.Column('away_wins', sa.Integer(), nullable=True),
    sa.Column('away_draws', sa.Integer(), nullable=True),
    sa.Column('away_losses', sa.Integer(), nullable=True),
    sa.Column('away_goals_for', sa.Integer(), nullable=True),
    sa.Column('away_goals_against', sa.Integer(), nullable=True),
    sa.Column('home_win_rate', sa.Float(), nullable=True),
    sa.Column('away_win_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_team_home_away_stats_id'), 'team_home_away_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_home_away_stats_id'), table_name='team_home_away_stats')
    op.drop_table('team_home_away_stats')
    # ### end Alembic commands ###
