"""Create team power ratings table

Revision ID: dd78c932b323
Revises: dae9e6dcd64b
Create Date: 2026-07-05 08:31:27.862783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd78c932b323'
down_revision: Union[str, Sequence[str], None] = 'dae9e6dcd64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_power_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('attack_power', sa.Float(), nullable=False),
    sa.Column('defense_power', sa.Float(), nullable=False),
    sa.Column('overall_power', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_team_power_ratings_id'), 'team_power_ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_power_ratings_id'), table_name='team_power_ratings')
    op.drop_table('team_power_ratings')
    # ### end Alembic commands ###
