"""Create team form table

Revision ID: f62518ba1b91
Revises: 49318102da5d
Create Date: 2026-07-03 23:20:42.282609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62518ba1b91'
down_revision: Union[str, Sequence[str], None] = '49318102da5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('last_five', sa.String(length=5), nullable=False),
    sa.Column('last_ten_points', sa.Integer(), nullable=False),
    sa.Column('current_win_streak', sa.Integer(), nullable=False),
    sa.Column('current_unbeaten_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_team_forms_id'), 'team_forms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_forms_id'), table_name='team_forms')
    op.drop_table('team_forms')
    # ### end Alembic commands ###
